### ISSUE TITLE
[Improvement] Flag player from postponed/cancelled game

### ISSUE THREAD

**Issue by rewgoes** [aaronliunumber2/timmies-helper#2]
Hi,

First of all, good job with the app. Well done! :)

With the pandemic, there are a few games that get cancelled during the day.

I think it's worth to remove players from postponed games from the list or at least flag them with some style or badge.

Let me know if you want some help implementing it, as I'm a developer as well. 

With a quick search I was able to find this API that might help identify if a game was postponed or not:
https://statsapi.web.nhl.com/api/v1/schedule

Example (Avalanche and Kings was cancelled today):
```json
"status": {
            "abstractGameState": "Preview",
            "codedGameState": "9",
            "detailedState": "Postponed",
            "statusCode": "9",
            "startTimeTBD": false
          }
```

I will need to investigate this API further to understand all the codes.

Stay safe!

**Comment by aaronliunumber2** [comment]
Hey you found me!! 

You are definitely not the first person to suggest flagging postponed games, and it's become even more "popular" since the canucks and avs just got their games postponed.  I'm working on adding them this weekend.

The NHL uses the same api that MLB uses and there is documentation here: https://github.com/toddrob99/MLB-StatsAPI/wiki/All-Functions

So far what I've needed to use is the same (of course stats are different).  You can read the schedule endpoint details here https://github.com/toddrob99/MLB-StatsAPI/wiki/Function:-schedule

**Comment by aaronliunumber2** [comment]
It's done!!! Needs some polish though.

Btw the code is really bad in the project overall, it was just for fun at first and then got popular, almost embarrassed for someone to have even looked at my code now
